version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: fastapi_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:


